name: Trigger auto deployment for budget-sharp

on:
  push:
    branches: 
      - main
    paths:
      - '**'
      - '.github/workflows/budget-sharp-AutoDeployTrigger-6d15ae5b-6694-485c-be42-d7a376e0b4fb.yml'

  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.BUDGETSHARP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BUDGETSHARP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BUDGETSHARP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/BudgetSharp.Api
          dockerfilePath: ${{ github.workspace }}/BudgetSharp.Api/Dockerfile
          registryUrl: budgetsharp.azurecr.io
          registryUsername: ${{ secrets.BUDGETSHARP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BUDGETSHARP_REGISTRY_PASSWORD }}
          containerAppName: budget-sharp
          resourceGroup: BudgetSharp
          imageToBuild: budgetsharp.azurecr.io/budget-sharp:${{ github.sha }}
          buildArguments: |
            BUILD_CONFIGURATION=Release
